services:
    redis:
        container_name: message-queue
        image: redis
        command: [redis-server, --maxmemory-policy, noeviction]
        env_file:
            - .env
        ports:
            - "127.0.0.1:${REDIS_PORT}:${REDIS_PORT}"
    monitor:
        container_name: monitor-service
        build:
            context: .
            dockerfile: ./monitor/Dockerfile
        env_file:
            - .env
        ports:
            - "127.0.0.1:${MONITOR_PORT}:${MONITOR_PORT}"
    transformer:
        container_name: transformer-service
        build:
            context: .
            dockerfile: ./transformer/Dockerfile
        env_file:
            - .env
        ports:
            - "127.0.0.1:${TRANSFORMER_PORT}:${TRANSFORMER_PORT}"
